### ISSUE TITLE
Link doesn't go anywhere.

### ISSUE THREAD

**Issue by Saekoboyy** [Slappy826/libndk-fixer#11]
![image:link location](https://github.com/user-attachments/assets/461c9160-d1c5-44f9-ad10-f0ed03067101)

![image:what happens when clicked](https://github.com/user-attachments/assets/874de296-b79c-4e03-abce-e0b4f1af1abd)

**Comment by Saekoboyy** [comment]
i also tried building the binary myself but that didn't work very well for me.

**Comment by katsu-chan** [comment]
I uploaded the result of github actions run (also fixed the file naming)

Here you go: https://github.com/katsu-chan/libndk-fixer/releases/tag/some-release

**Comment by Slappy826** [comment]
Yeah github seems to remove action artifacts after 90 days, sorry! The link @katsu-chan posted should probably work.

**Comment by Saekoboyy** [comment]
It does, tysm!
