### ISSUE TITLE
Instantly crashes instead of going to white screen.

### ISSUE THREAD

**Issue by Slayer5934** [Slappy826/libndk-fixer#3]
https://github.com/waydroid/waydroid/issues/1323

**Comment by Slappy826** [comment]
This doesnt appear to be an issue with this repo.

**Comment by iFlxy** [comment]
> This doesnt appear to be an issue with this repo.

works on my machine™

**Comment by Slayer5934** [comment]
You are correct, the fix was to install the playstore version (Arm64)
