### ISSUE TITLE
The /var/lib/waydroid/overlay/system/lib64 directory does not exist for me

### ISSUE THREAD

**Issue by Caxtonis** [Slappy826/libndk-fixer#6]
On my system (Arch), i can only go up to /var/lib/waydroid/overlay/ (theres only an empty vendor directory in there). Manually adding the system/lib64 directories and then putting libndk-fixer.so inside doesnt seem to work

**Comment by Slappy826** [comment]
The only things I can think of is to ensure you correctly installed libndk using [waydroid_script](https://github.com/casualsnek/waydroid_script) (and not libhoudini), and to not have waydroid running while installing this.

If you want better help, I'd recommend joining the Vinegar discord [here](https://discord.gg/dzdzZ6Pps2). There is a thread in the helpdesk forum channel where you will find me or others who can potentially better help you.
