### ISSUE TITLE
Black screen on Arch Linux + sway

### ISSUE THREAD

**Issue by trustytrojan** [Slappy826/libndk-fixer#8]
I'm getting a black screen. However, the interactive elements (email & password text-inputs, login/signup buttons, and ToS/Privacy buttons/links) do work when I click around for them. I was able to even login to my account one time, but of course, the homepage was also a black screen, and I couldn't tell after that what I was clicking.

Attached is the output of `waydroid logcat | grep ndk` on a fresh Waydroid install with the `GAPPS` image, `libndk` installed via [waydroid_script](https://github.com/casualsnek/waydroid_script), and with `libndk_fixer.so` installed as instructed (`waydroid_base.prop` edited as instructed as well).

[waydroid_logcat.txt](https://github.com/user-attachments/files/16110861/waydroid_logcat.txt)

**Comment by Slappy826** [comment]
While this isn't an issue with my fix, I do know a solution for your problem.

```
open /var/lib/waydroid/waydroid_base.prop
find ro.hardware.gralloc=gbm
replace with ro.hardware.gralloc=minigbm_gbm_mesa
```

That should specifically fix getting a black screen when opening the app. Would recommend any further questions be asked in the [vinegar discord](https://discord.gg/dzdzZ6Pps2), as I don't check this very often.

**Comment by trustytrojan** [comment]
Thanks, that made it work. Performance isn't great but I'm not surprised considering how much instruction translation has to occur on this old PC.
